# PyTorch Tensors

In order to get anything done with deep learning, we need some way to store and manipulate data. 
Therefore, to start, we develop proficiency with the n-dimensional array in PyTorch, which is also called the tensor.

In [2]:
import torch

### Exercise 1A:
Create in the next code cell a 32-bit floating point torch Tensor of shape `(4,5)` which is filled with square root of 29.

In [3]:
tensor = torch.full((4, 5), torch.sqrt(torch.tensor(29.0)), dtype=torch.float32)
tensor

tensor([[5.3852, 5.3852, 5.3852, 5.3852, 5.3852],
        [5.3852, 5.3852, 5.3852, 5.3852, 5.3852],
        [5.3852, 5.3852, 5.3852, 5.3852, 5.3852],
        [5.3852, 5.3852, 5.3852, 5.3852, 5.3852]])

### Exercise 1B:

Convert the tensor created in the previous exercise to 64-bit floating point.

In [4]:
tensor = tensor.to(dtype=torch.float64)
tensor

tensor([[5.3852, 5.3852, 5.3852, 5.3852, 5.3852],
        [5.3852, 5.3852, 5.3852, 5.3852, 5.3852],
        [5.3852, 5.3852, 5.3852, 5.3852, 5.3852],
        [5.3852, 5.3852, 5.3852, 5.3852, 5.3852]], dtype=torch.float64)

### Exercise 2:
Create a tensor `x` (you can give it the shape you want) such that its elements are sampled from a normal distribution of mean 3 and variance 2.

Next, create a tensor `y` having the same shape as `x` such that its elements are sampled from a uniform distribution between -1 and 2. Your code should be robust to the shape of `x` such that if you change the shape of `t`, the shape of your `y` should adapt!

In [8]:
x = torch.normal(mean=3.0, std=torch.sqrt(torch.tensor(2.0)), size=(3, 4))
y = torch.distributions.Uniform(-1, 2).sample(x.shape)
x,y

(tensor([[1.4745, 1.0296, 1.0502, 2.8298],
         [1.4752, 3.2231, 1.6685, 3.7533],
         [0.5909, 3.2739, 1.7187, 4.1239]]),
 tensor([[ 1.2772,  0.3217, -0.2400, -0.7849],
         [ 0.9439,  0.8879,  1.8247,  0.2922],
         [-0.8566,  1.0425,  1.4151, -0.9638]]))

### Exercise 3:

Run `A / A.sum(axis=1)` for the following tensor A and see what happens. Can you analyze the reason? Create a text cell to provide your answer.

In [4]:
A = torch.arange(20, dtype=torch.float32).reshape(4, 5)
A/ A.sum(axis=1)
A

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

We are trying to divide a (4, 5) tensor (2D) by a (4,) tensor (1D), which cannot be broadcast directly across columns. If the sum shape is (4,1) it would then be possible to perform row division across columns.

### Exercise 4:

As with an ordinary Python array, we can access the length of a tensor by calling Python’s built-in `len()` function.

In [9]:
x = torch.arange(4)
len(x)

4

We now define a tensor `X` of shape `(2, 3, 4)` . What is the output of `len(X)`? Can you analyse the reason for the output? Create a text cell to provide your answer.

In [10]:
X = torch.arange(24).reshape(2, 3, 4)
len(X)

2

The output is 2 because len(X) always returns the size of the first dimension of the tensor, which corresponds to the number of 2D matrices in the 3D tensor.

### Exercise 5:

We have seen examples of PyTorch `Tensor` broadcasting.

In [6]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(5)
a.shape, b.shape

(torch.Size([3, 1]), torch.Size([5]))

In [7]:
a + b


tensor([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

Replace the two tensors in the broadcasting mechanism with different shapes of 3 or 4-dimensional tensors. For example `a = torch.empty(5,2,4,1)`,
`b = torch.empty(3,1,1)`. Is the result the same as expected? Analyse the results. Come up with 3D or 4D tensors with different sizes at each dimension. Can you come up with the rules with examples which are required for Tensor broadcasting to work? Creat a text block to provide your analysis.

In [12]:
a = torch.empty(5, 2, 4, 1)
b = torch.empty(3, 1, 1)

a.shape , b.shape

(torch.Size([5, 2, 4, 1]), torch.Size([3, 1, 1]))

In [13]:
a+b

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

Broadcasting lets us perform operations on tensors of different shapes by automatically expanding their dimensions where possible. The rules are:

- Start comparing shapes from the last dimension (from the end)
- For each pair of dimensions:
    - If they’re equal, that’s fine.
    - If one of them is 1, that’s also fine (it can be stretched to match).
    - If neither of these is true, the tensors can’t be broadcasted.

- If one tensor has fewer dimensions, it’s treated as if it has extra 1s on the left.


Example 1: 
- Tensors a: (5, 2, 4, 1), b: (2, 1, 1)
- Aligning shapes from the end:
    a: 5  2  4  1  
    b:    2  1  1  <-- implicitly becomes (1, 2, 1, 1)
- Since all dimensions are compatible, b will be broadcasted to match a: (5, 2, 4, 1)

Example 2:
- Tensors a: (5, 2, 4, 1), b: (3, 1, 1) as seen in the previous cell. The reason we got the unexpected output will be clear when we align shapes from the end:
    1 vs 1 -> Ok
    4 vs 1 -> Ok
    2 vs 3 -> Not compatible (neither is 1 nor equal)

Hence we get the output.

### Exercise 6:

Create a one dimensional tensor `x` containing the numbers `0` to `23` in order.
Reshape x in the next code cell to create the following tensor:

```
tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
             [ 4,  5,  6,  7, 16, 17, 18, 19],
             [ 8,  9, 10, 11, 20, 21, 22, 23]])
```





In [9]:
x = torch.arange(24)
#x
x_re = torch.cat([
    x[:12].reshape(3, 4),   # elements 0–11 with 3 rows, 4 columns
    x[12:].reshape(3, 4)    # elements 12–23 with 3 rows, 4 columns
], dim=1)  # concatenate them
x_re

tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
        [ 4,  5,  6,  7, 16, 17, 18, 19],
        [ 8,  9, 10, 11, 20, 21, 22, 23]])

### Exercise 7:

A one-hot vector for an integer $n$ is a vector that has a one in its $n$th slot, and zeros in all other slots. One-hot vectors are used to represent categorical variables in machine learning.

Implement a function in the following code cell that creates a 2D PyTorch tensor of one-hot row vectors from a list of Python integers.

For example, given a list `[1, 2, 3, 3]` of integers, your function should produce the 2D tensor:

```
[[0 1 0 0],
 [0 0 1 0],
 [0 0 0 1],
 [0 0 0 1]]
```



In [14]:
def one_hot_vector(x):
  num_classes = max(x) + 1
  one_hot_vectors = torch.zeros((len(x), num_classes))
  for i, integer in enumerate(x):
    one_hot_vectors[i][integer] = 1
  return one_hot_vectors

x = [1, 2, 3, 3]
print(one_hot_vector(x))

tensor([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]])


### Exercise 8:

Use the GPU to accelerate multiplication of the following large 2D PyTorch tensors. First perform the multiplication on CPU. Next perform the computation on GPU. Compare the time required for mulplication on CPU vs GPU.

In [16]:
x = torch.rand(1024, 4096) # 2 random tensors
y = torch.rand(4096, 8192)
start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)

start.record()
result_cpu = torch.matmul(x, y)
end.record()
torch.cuda.synchronize()
print(f"CPU time: {start.elapsed_time(end)} ms")

x = x.cuda()
y = y.cuda()

start.record()
result_gpu = torch.matmul(x, y)
end.record()
torch.cuda.synchronize()
print(f"GPU time: {start.elapsed_time(end)} ms")

CPU time: 138.66188049316406 ms
GPU time: 4.7409281730651855 ms


### Exercise 9: 

Create a function to compute the number of negative values in a tensor.
Your code should not use any loops. After implementing the function, test your function with input PyTorch tensors of different shapes.

In [18]:
def negative_value_count(x):
  # pass # replace pass with your code
    return (x < 0).sum().item() 

x1 = torch.tensor([[1, -2, 3], [-4, 5, -6]])  #test
x2 = torch.tensor([[-1, 2, 3], [4, -5, 6], [-7, 8, -9]])
x3 = torch.randn(10, 5)


print(f"Negative values in x1: {negative_value_count(x1)}")
print(f"Negative values in x2: {negative_value_count(x2)}")
print(f"Negative values in x3: {negative_value_count(x3)}")

Negative values in x1: 3
Negative values in x2: 4
Negative values in x3: 24


### Exercise 10:

Create a function which returns the copy of the input tensor but with maximum value along each column set to `-1`.

  For example:

```
 x = torch.tensor([
        [12, 21, 1],
        [ 4,  7,  20]
      ])
```


  Then `y = negative_max_column(x)` should be:
 
  ```
torch.tensor([
    [-1, -1, 1],
    [4,  7,  -1]
  ])
```


Your code should not use any loops. Test your function with some examples.

In [21]:
def negative_max_column(x):
  # pass # replace pass with your code
    column_max, _ = torch.max(x, dim=0, keepdim=True)
    neg = torch.where(x == column_max, torch.full_like(x, -1.0), x)
    return neg


#test 1
x1 = torch.tensor([
    [12, 21, 1],
    [4, 7, 20]
])

#test 2
x2 = torch.tensor([
    [5, 8, 3],
    [5, 2, 3]
])

#test 3
x3 = torch.tensor([
    [-1, 0, -3],
    [-2, 0, 4],
    [0, -5, 4]
])

test_tensors = [x1, x2, x3]

for i, x in enumerate(test_tensors, 1):
    y = negative_max_column(x)
    print(f"Test {i} output:\n{y}\n")

Test 1 output:
tensor([[-1, -1,  1],
        [ 4,  7, -1]])

Test 2 output:
tensor([[-1, -1, -1],
        [-1,  2, -1]])

Test 3 output:
tensor([[-1, -1, -3],
        [-2, -1, -1],
        [-1, -5, -1]])



### Exercise 11:

Write a function to subtract the mean of each row from a 2D tensor. Your code should not use any loops. Test your function with some examples.

Example 1:
For the following input tensor:
`tensor([[1,0],[0,4]])`
The desired output is the following:
`tensor([[0.5000,−0.5000],[−2.0000,2.0000]])`

Example 2:
For the following input tensor:
`tensor([[.5,0,0],[0,.3,0],[0,0,8]])`

The desired output is the following:
`tensor([[0.3333,−0.1667,−0.1667],[−0.1000,0.2000,−0.1000],[−2.6667,−2.6667,5.3333]])`

In [16]:
def subtract_row_mean(x):
  # pass # replace pass with your code
    row_mean = torch.mean(x, dim=1, keepdim=True)  # (mean of each row ,1) dim for broadcasting
    return x - row_mean

#test
x1 = torch.tensor([[1, 0], [0, 4]], dtype=torch.float32)
y1 = subtract_row_mean(x1)
print(y1)

x2 = torch.tensor([[0.5, 0, 0], [0, 0.3, 0], [0, 0, 8]], dtype=torch.float32)
y2 = subtract_row_mean(x2)
print(y2)

tensor([[ 0.5000, -0.5000],
        [-2.0000,  2.0000]])
tensor([[ 0.3333, -0.1667, -0.1667],
        [-0.1000,  0.2000, -0.1000],
        [-2.6667, -2.6667,  5.3333]])


### Exercise 12:

Feed a tensor with 3 or more dimensions to the `linalg.norm` function and observe its output. What does this function compute for tensors of arbitrary shape? Explain in a block below.

In [17]:
x = torch.rand(2, 3, 4)
norm_x = torch.linalg.norm(x)

print(x)
print("\nNorm:", norm_x)

tensor([[[0.3659, 0.1557, 0.1604, 0.8375],
         [0.5451, 0.2398, 0.0023, 0.4335],
         [0.9359, 0.0206, 0.9614, 0.6242]],

        [[0.6369, 0.8481, 0.7283, 0.0200],
         [0.9259, 0.9430, 0.2128, 0.2967],
         [0.8710, 0.1603, 0.9522, 0.5806]]])

Norm: tensor(3.0302)


linalg.norm computes the norm of a matrix (if dim is a 2d tuple)/vector (if dim is int). There's customizations for the type of norm that can be computed. The torch.linalg.norm function calculates the Frobenius norm for tensors of arbitrary dimensions as follows:

- Flatten the tensor into a 1D tensor.
- Calculate the sum of the absolute squares of its elements.
- Take the square root of the sum.

### Exercise 13: 

Implement a function that takes in two $2 \mathrm{D}$ tensors $A$ and $B$ and returns the column sum of A multiplied by the sum of all the elmements of $\boldsymbol{B}$, i.e., a scalar, e.g.,
If $A=\left[\begin{array}{ll}1 & 1 \\ 1 & 1\end{array}\right]$ and $B=\left[\begin{array}{lll}1 & 2 & 3 \\ 1 & 2 & 3\end{array}\right]$ then $O u t=\left[\begin{array}{ll}2 & 2\end{array}\right] \cdot 12=\left[\begin{array}{ll}24 & 24\end{array}\right]$

In [22]:
def add_and_multiply(A,B):
  A_col_sum = torch.sum(A, dim=0)
  B_sum = torch.sum(B)
  return A_col_sum * B_sum

A = torch.tensor([
    [1,1],
    [1 ,1]
    ])
B = torch.tensor([
    [1,2,3],
    [1 ,2,3,]
    ])
output = add_and_multiply(A,B)
print(f"Output for A * B is {output}")

x1 = torch.tensor([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
],dtype=torch.float32)

x2 = torch.tensor([
    [-1, -1, -1],
    [2, 2, 2],
    [-4, -4, -4]
],dtype=torch.float32)
output_1 = add_and_multiply(x1,x2)
print(f"Output for x1 * x2 is {output_1}")


Output for A * B is tensor([24, 24])
Output for x1 * x2 is tensor([-27., -54., -81.])


### Exercise 14:

Implement a function that takes in a square matrix $A$ and returns a $2 D$ tensor consisting of a flattened $A$ with the index of each element appended to this tensor in the row dimension, e.g.,
If $A=\left[\begin{array}{cc}2 & 3 \\ -1 & 10\end{array}\right]$ then $O u t=\left[\begin{array}{cc}0 & 2 \\ 1 & 3 \\ 2 & -1 \\ 3 & 10\end{array}\right]$

In [23]:
def flaten_and_append(A):
  assert A.shape[0] == A.shape[1]  #square matrix as input
  indices = torch.arange(torch.numel(A)).reshape(-1,1)
  A_flat = torch.flatten(A).reshape(-1,1)
  output = torch.cat((indices, A_flat),dim=1)
  return output

A = torch.tensor([[2, 3],
                  [-1, 10]], dtype=torch.float32)

output = flaten_and_append(A)
output

tensor([[ 0.,  2.],
        [ 1.,  3.],
        [ 2., -1.],
        [ 3., 10.]])

### Exercise 15:

Implement a function that takes in two $2 D$ tensors $A$ and $B$. If the shapes allow it, this function returns the elementwise sum of $A$-shaped $B$, and $B$; else this function returns a 1D tensor that is the concatenation of the two tensors, e.g.,
If $A=\left[\begin{array}{cc}1 & -1 \\ -1 & 3\end{array}\right]$ and $B=\left[\begin{array}{llll}2 & 3 & 0 & 2\end{array}\right]$ then $O u t=\left[\begin{array}{cc}3 & 2 \\ -1 & 5\end{array}\right]$
If $A=\left[\begin{array}{cc}1 & -1 \\ -1 & 3\end{array}\right]$ and $B=\left[\begin{array}{ccc}2 & 3 & 0\end{array}\right]$ then $O u t=\left[\begin{array}{ccccccc}1 & -1 & -1 & 3 & 2 & 3 & 0\end{array}\right]$

In [26]:
def combine_tensors(A, B):
    try:
        B_shaped = B.reshape(A.shape)
        output = A + B_shaped
    except RuntimeError:
        output = torch.cat((A.flatten(), B.flatten()))
    return output

A1 = torch.tensor([[1, -1],
                   [-1, 3]], dtype=torch.float32)

B1 = torch.tensor([2, 3, 0, 2], dtype=torch.float32)

output1 = combine_tensors(A1, B1)
print(output1)

A2 = torch.tensor([[1, -1],
                   [-1, 3]], dtype=torch.float32)

B2 = torch.tensor([2, 3, 0], dtype=torch.float32)

output2 = combine_tensors(A2, B2)
print(output2)

tensor([[ 3.,  2.],
        [-1.,  5.]])
tensor([ 1., -1., -1.,  3.,  2.,  3.,  0.])


### Exercise 16:

You are given a tensor `samples` with 12 sequences of length 15. Adapt the code below to add a `new_sample` to `samples` tensor.



In [28]:
samples = torch.randn(size=(12, 15))
new_sample = torch.randn(size=(15,))

new_sample = new_sample.unsqueeze(0) #add dim 1 to the new_sample tensor
samples = torch.cat((samples, new_sample), dim=0)
samples

tensor([[-5.1355e-01,  2.4170e+00,  1.6826e-01,  1.6043e+00,  7.1901e-01,
         -1.1538e-02,  8.6024e-01,  1.6311e+00,  3.0585e-01,  8.7563e-01,
         -7.5413e-01, -1.5059e+00, -2.4381e+00, -1.8494e-01, -1.4239e-01],
        [-3.8149e-01,  3.0317e-01, -5.8626e-01, -1.2470e+00,  1.8724e+00,
          1.1002e+00, -4.9279e-01, -4.2162e-01,  3.3764e-01, -2.5314e-01,
          6.8918e-01, -1.0707e+00, -3.9977e-01, -7.9596e-01, -2.5736e-01],
        [-3.0031e-01,  5.6112e-01, -3.6882e-01, -1.4406e-01, -2.9724e-01,
          1.3576e+00, -8.4231e-01, -1.5052e+00,  4.1953e-02, -6.1958e-01,
         -1.6105e+00,  5.4606e-01,  1.0497e+00,  4.0686e-01,  1.2197e+00],
        [-1.3175e+00,  7.8250e-02, -5.1606e-01, -1.6556e-01,  1.4412e+00,
          1.0966e+00,  1.1626e+00, -1.2632e+00, -8.4339e-01,  2.0194e-01,
         -9.9883e-01,  8.9911e-01, -2.3282e-01,  1.8972e+00, -6.8810e-01],
        [-1.3735e+00,  1.3747e+00,  2.0008e-02,  1.2616e-01,  2.1671e+00,
         -7.2217e-01,  5.9229e-02,

### Exercise 17:

Suppose you have a tensor `images_tensor` containing  a batch of `n_batch` number of images of resolution: 30x30 pixels. `images_tensor` is thus of shape `(n_batch, 1, 30, 30)`

Write a function `flatten_images` that convert `images_tensor` into a tensor containing flattened images (i.e. a tensor of shape: `(n_batch, 1*30*30)`.

In [29]:
def flatten_images(images_tensor):
    # images_tensor shape: (batch_size, channels, height, width)
    n_batch, c, h, w = images_tensor.shape
    # Flatten each image into a vector: (batch_size, channels*height*width)
    flattened_img_tensor = images_tensor.view(n_batch, -1)
    return flattened_img_tensor

In [30]:
n_batch = 5
images_tensor = torch.randn(size=(n_batch, 1, 30, 30))
flattened_images = flatten_images(images_tensor)
print(flattened_images.shape)

torch.Size([5, 900])
